#pragma once
#include <iostream>
#include "ConsoleWindow.h"
#include <math.h>
#include <time.h>
#include "Vector2.h"
#include "Board.h"
#include <stdlib.h> 
#include <string>
#include <windows.h>
#include <mmsystem.h>
#include <conio.h>
#include <fstream>
#include "AI.h"
#include "Settings.h"
#include "PhysicsObject.h"
#include "RigidBody.h"
#include "BackgroundObj.h"
#include "Background.h"
#include "Characters.h"
#include "Artwork.h"
#include "AssetsClass.h"
#include "CustomAsset.h"
#include "CustomAnimationAsset.h"
#include <windows.h>
#include <objidl.h>
#include <gdiplus.h>
#include "ReiventTheWheel.h"
#include "Concerto.h"
#include "SYDEWindowGame.h"
#include "SYDEGamePlay.h"
#include "SYDETime.h"
#include <chrono>
#include "SYDETextBox.h"